### ISSUE TITLE
1a5: Map key components of queries to ontologies

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#14] opened 2019-12-11 01:22 UTC
Depends on #13

**Comment by nicolevasilevsky** [comment] 2019-12-13 19:14
This is done:
https://docs.google.com/spreadsheets/d/1jVai85S3CYsQXcOpxk1KlxcUNLJS0y1ag8Q5x_hK93Y/edit#gid=859956776

**Comment by nicolevasilevsky** [comment] 2019-12-17 21:31
can this be closed?

**Comment by ShahimEssaid** [comment] 2019-12-18 12:36
If issues are closed they will be removed from the boards. Correct? If that's the case we probably should be closing these types of issues since we want them to remain on the boards as finished/completed. Maybe we can use labels to organize some of this.  Maybe at the end of a phase we can close them as we prepare the next set of issues for the next phase, and link to the previous and now closed issues from the previous phase.

**Comment by gaurav** [comment] 2019-12-18 15:58
Since the [terminologies WS](https://github.com/orgs/cancerDHC/projects/2#card-30691590) has a "Done" column, closing this issue should automatically move it into that column. So it'll still be visible on the board as completed. We could create additional "Done in Phase 1", "Done in Phase 2" columns if it's important to keep track of when each task was completed.

**Comment by nicolevasilevsky** [comment] 2020-01-02 18:24
@ShahimEssaid actually, I think if the issue is closed, you can still see it on the board. We can also move this to the done column.

**Closed by nicolevasilevsky** 2020-01-02 18:24 UTC
Labels: Terminology
